name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal --configuration Release --logger trx
    - name: Unit Test Results
      uses: NasAmin/trx-parser@v0.2.0
      with:
        TRX_PATH: test/JustEvaluate.Tests/TestResults/*.trx
        REPO_TOKEN: ${{ github.token }}
        IGNORE_FAILURE: false
